service: authorization-service
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

custom:
  dotenv:
    required:
      file: true
  webpack:
    packager: "yarn"

functions:
  basicAuthorizer:
    handler: src/handlers/basicAuthorizer.handler

resources:
  Outputs:
    BasicAuthorizerArn: {
      Value: {
        "Fn::GetAtt": [ "BasicAuthorizerLambdaFunction", "Arn" ]
      },
      Export: {
        Name: 'BasicAuthorizerArn'
      }
    }