service: bff-proxy
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  cart-api-proxy:
    handler: absurd.hanlder
    events:
      - http:
          method: any
          path: /{proxy+}
          integration: http_proxy
          request:
            uri: http://generalov-bff-api-devel.us-east-1.elasticbeanstalk.com/{proxy}
            parameters:
              paths:
                proxy: true

